runtime: nodejs16 # or another supported version

instance_class: F2

env_variables:
  dbpass: "i7YsFs2f&B"

handlers:
- url: /stylesheets
  static_dir: stylesheets

- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto
